### ISSUE TITLE
Playtest comments

### ISSUE THREAD

**Issue by Umaimi** [Doreen03/Lola-s-Learning#3]
Bug:
- You can access the next classroom by touching any part of the hallway’s right wall rather than the door gap

Suggestion:
- More jump scares plsss

Calysta

**Comment by GoldyBlocksLOL** [comment]
Thanks for letting us know about this bug!

Since we haven't had time to add the boundaries for the hallway world yet, you can walk through the door in the black area, as well. This is because the image of the door is really tall, as shown in the image below:
![door10](https://user-images.githubusercontent.com/89648753/145495043-e3c4bd2a-32f2-4fc5-92a6-e53099677067.png)

Also, I'd love if we added more jumpscares if we had more time!! That would be really cool. (Although, I'm scared of jumpscares lol)

Thanks,
Amanda
