### ISSUE TITLE
Bug when Actor goes in the black session

### ISSUE THREAD

**Issue by leonellalevy** [Doreen03/Lola-s-Learning#5]
Hey!
By the way, good job with your game! So I notice when I go to the black section, the game just stop. Here are the steps I took to make it happen:
-Launch game
-Move up until the edge

The game just stops and I had to click again on run to continue. 

Good luck fixing it!

Leonella Levy Martel

**Comment by leonellalevy** [comment]
Another comment, when I was playing the game, a question was who is the artist that will win the best seller in 3023 or something like that, but there was not right answer.

**Comment by GoldyBlocksLOL** [comment]
Hey!

So the point of the question for "who will be the best seller" is that there is no right answer and it forces the player to get booted to the next level (so that it progresses the story)
It's supposed to seem like the game is glitching out and you can't do anything about it.

Also, we're planning on adding the boundaries into the hallways so you can't walk into the black area. Thanks for the feedback!!
